### ISSUE TITLE
How to to include server.cc and client.cc files in my code

### ISSUE THREAD

**Issue by Yash9829** [lowRISC/boringssl#1]
I tried to use server.cc and client.cc in my code, in server.cc there is a function called server which takes args, I tried to write a main function and calling server in that main function by passing the arguments( I passed an empty string in optional arguments from that karguments) but I couldn't able to run the code it is giving undefined reference errors, so could someone help me with this and also if anyone has a code for a sample client and server using boringssl library please share it along with compilation steps

**Comment by rswarbrick** [comment]
Hi there! This repository is just a mirror of https://boringssl.googlesource.com/boringssl/. Probably, that's the best place to raise bug reports.
